import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {defaults,atomicJSON,readJSON,loadConfig,saveConfig,workspace,validateConfig} from '../runtime/config.mjs';
import {createConversation,getConversation,submitTurn,executeConversation,conversationQueue,cancelConversation,onboardingDraft,previewOnboarding,completeOnboarding,parseConversationResponse,conversationContext,applyConversationAction,recoverConversationJob,handleConversationRequest,conversationEvents} from '../runtime/conversations.mjs';
import {enqueue,executeJob,nextQueuedJob,jobsFor,contextFor} from '../runtime/jobs.mjs';
import {PACKS,importPack} from '../runtime/packs.mjs';
import {sourcesFor,importBuffer} from '../runtime/sources.mjs';

function env(t,{configured=false}={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'argus-conversation-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const c={...defaults(),provider:'codex',onboarded:configured};saveConfig(c,root);return {root,c,dir:workspace(c,root),queue:conversationQueue(root)};}
const message=(text,answers={},actions=[])=>JSON.stringify({text,spokenText:text.slice(0,500),answers,actions});
async function reply(env,session,text,output){const submitted=submitTurn(session.id,text,crypto.randomUUID(),env.c,env.root);await executeConversation(env.queue,env.c,submitted.job,async()=>output,{root:env.root});return getConversation(session.id,env.c,env.root);}

test('v1 migration backs up exact old data and does not re-onboard existing users',t=>{
  const {root}=env(t),old={...defaults(),version:1,onboarded:true,name:'Existing student',goals:['Preserve my work'],provider:'claude',voice:{...defaults().voice,speed:1.3},metrics:[]};delete old.appearance;delete old.businessProfile;delete old.features;atomicJSON(path.join(root,'.argus-config.json'),old);
  const migrated=loadConfig(root);assert.equal(migrated.version,2);assert.equal(migrated.onboarded,true);assert.equal(migrated.voice.speed,1.3);assert.deepEqual(migrated.goals,old.goals);const backups=fs.readdirSync(path.join(root,'.argus-local/backups'));assert.equal(backups.length,1);assert.deepEqual(readJSON(path.join(root,'.argus-local/backups',backups[0])),old);loadConfig(root);assert.equal(fs.readdirSync(path.join(root,'.argus-local/backups')).length,1);
});
test('appearance and business settings validate known choices and omit unknown keys',()=>{const c=validateConfig({...defaults(),appearance:{theme:'dark',unknown:'drop'},businessProfile:{businessName:'Studio',definitions:{Qualified:'Has budget'},unknown:'drop'}});assert.equal(c.appearance.theme,'dark');assert.equal(c.businessProfile.definitions.Qualified,'Has budget');assert.equal(c.appearance.unknown,undefined);assert.equal(c.businessProfile.unknown,undefined);assert.throws(()=>validateConfig({...c,appearance:{theme:'neon'}}));assert.throws(()=>validateConfig({...c,features:[{id:'../escape',activeVersion:'x'}]}));});
test('onboarding lives outside unconfirmed workspace and resumes the same session',t=>{const e=env(t),s=createConversation('onboarding',e.c,e.root);assert.equal(fs.existsSync(e.dir),false);assert.equal(createConversation('onboarding',e.c,e.root).id,s.id);assert.notEqual(createConversation('onboarding',e.c,e.root,{fresh:true}).id,s.id);assert.equal(onboardingDraft(e.root).stage,'interview');});
test('interview remembers combined answers, optional appearance and user defaults without source access',async t=>{
  const e=env(t),s=createConversation('onboarding',e.c,e.root);await reply(e,s,'I run a studio for local shops. You decide the look.',message('Let’s start with a delivery overview. Where do projects get delayed?',{businessProfile:{businessName:'Studio',audience:'Local shops',offering:'Design services'},appearance:{theme:'light'},starterPack:'agency'}));
  await reply(e,s,'Approvals take too long.',message('What should your first overview help you decide?',{businessProfile:{problem:'Slow approvals'}}));
  const saved=getConversation(s.id,e.c,e.root),draft=onboardingDraft(e.root);assert.equal(saved.turns.filter(t=>t.role==='user').length,2);assert.equal(saved.turns.filter(t=>t.role==='assistant').length,3);assert.equal(draft.answers.businessProfile.offering,'Design services');assert.equal(draft.answers.businessProfile.problem,'Slow approvals');assert.equal(draft.answers.appearance.theme,'light');assert.equal(fs.existsSync(e.dir),false);
});
test('requests deduplicate by ID, reject altered reuse and retain one pending turn',t=>{const e=env(t),s=createConversation('onboarding',e.c,e.root),a=submitTurn(s.id,'Hello','request-1',e.c,e.root),b=submitTurn(s.id,'Hello','request-1',e.c,e.root);assert.equal(a.job.id,b.job.id);assert.equal(b.session.turns.length,2);assert.throws(()=>submitTurn(s.id,'Changed','request-1',e.c,e.root),/different message/);assert.throws(()=>submitTurn(s.id,'Next','request-2',e.c,e.root),/current reply/);});
test('invalid structured replies preserve the previous answers and support explicit retry',async t=>{const e=env(t),s=createConversation('onboarding',e.c,e.root);previewOnboarding({name:'Alex'},e.c,e.root);await reply(e,s,'Help me','{"text":"Okay","answers":{"name":"Changed"},"actions":[{"type":"run_shell"}]}');assert.equal(onboardingDraft(e.root).answers.name,'Alex');assert.equal(getConversation(s.id,e.c,e.root).status,'error');assert.equal(getConversation(s.id,e.c,e.root).pendingJobId,null);await reply(e,s,'Try again',message('What would you like to accomplish?'));assert.equal(getConversation(s.id,e.c,e.root).status,'idle');});
test('interruption suppresses obsolete replies and late onboarding changes',async t=>{const e=env(t),s=createConversation('onboarding',e.c,e.root),{job}=submitTurn(s.id,'Hello','request',e.c,e.root);await executeConversation(e.queue,e.c,job,async()=>{cancelConversation(s.id,e.c,e.root);return message('Late answer',{name:'Too late'});},{root:e.root});assert.equal(getConversation(s.id,e.c,e.root).turns.length,2);assert.equal(onboardingDraft(e.root).answers.name,undefined);assert.equal(jobsFor(e.queue)[0].status,'cancelled');});
test('provider failure and runner restart keep conversation recoverable',async t=>{const e=env(t),s=createConversation('conversation',e.c,e.root),{job}=submitTurn(s.id,'Hello','r1',e.c,e.root);await executeConversation(e.queue,e.c,job,async()=>{throw new Error('Account usage limit');},{root:e.root});assert.match(getConversation(s.id,e.c,e.root).error,/usage limit/);const next=submitTurn(s.id,'Again','r2',e.c,e.root);recoverConversationJob(next.job,e.c,e.root);assert.equal(getConversation(s.id,e.c,e.root).pendingJobId,null);assert.match(getConversation(s.id,e.c,e.root).error,/restarted/);});
test('brief completion preserves answers and vault notes, migrates transcript, and separates first result',async t=>{
  const e=env(t),s=createConversation('onboarding',e.c,e.root),vault=path.join(e.root,'My vault');fs.mkdirSync(vault);fs.writeFileSync(path.join(vault,'Existing.md'),'Keep this note');await reply(e,s,'My business is Studio',message('What would you like first?',{businessProfile:{businessName:'Studio'}}));
  previewOnboarding({name:'Alex',starterPack:'agency',useDemo:true,vault},e.c,e.root);assert.equal(loadConfig(e.root).onboarded,false);const done=await completeOnboarding({},e.c,e.root),c=loadConfig(e.root);assert.equal(c.onboarded,true);assert.equal(c.workspace,path.join(fs.realpathSync(vault),'ARGUS'));assert.equal(c.businessProfile.businessName,'Studio');assert.equal(onboardingDraft(e.root).answers.name,'Alex');assert.equal(getConversation(s.id,c,e.root).turns.length,3);assert.equal(fs.readFileSync(path.join(vault,'Existing.md'),'utf8'),'Keep this note');assert.equal(c.firstResult.status,'pending');assert.equal(sourcesFor(workspace(c,e.root))[0].origin,'demo:pack:agency');
  await executeJob(workspace(c,e.root),c,done.firstJob,async()=>{throw new Error('Provider offline');},{root:e.root});assert.equal(loadConfig(e.root).onboarded,true);assert.equal(loadConfig(e.root).firstResult.status,'pending');
});
test('workspace changes with actual data are blocked before committing settings',async t=>{const e=env(t);fs.mkdirSync(e.dir);fs.writeFileSync(path.join(e.dir,'notes.md'),'Keep');await assert.rejects(()=>completeOnboarding({workspace:'elsewhere'},e.c,e.root),/already contains data/);assert.equal(loadConfig(e.root).workspace,'workspace');assert.equal(loadConfig(e.root).onboarded,false);});
test('completing during a reply cancels that interview before configuration is applied',async t=>{const e=env(t),s=createConversation('onboarding',e.c,e.root),{job}=submitTurn(s.id,'Almost done','r1',e.c,e.root);await executeConversation(e.queue,e.c,job,async()=>{await completeOnboarding({name:'Alex'},e.c,e.root);return message('Late',{name:'Changed'});},{root:e.root});assert.equal(loadConfig(e.root).name,'Alex');assert.equal(onboardingDraft(e.root).stage,'complete');assert.equal(getConversation(s.id,loadConfig(e.root),e.root).pendingJobId,null);});
test('local actions require explicit apply, deduplicate and queue build previews',async t=>{
  const e=env(t,{configured:true}),s=createConversation('conversation',e.c,e.root);const session=await reply(e,s,'Create a task and build a tracker',message('I can prepare those.',{},[{type:'task',title:'Review pipeline'},{type:'build_feature',title:'Build sales tracker',prompt:'Build a simple sales tracker with demonstration records.',sourceIds:[]}]));assert.equal(fs.existsSync(path.join(e.dir,'system/tasks.json')),false);const turn=session.turns.at(-1),a=turn.actions[0];applyConversationAction(s.id,turn.id,a.id,e.c,e.root);applyConversationAction(s.id,turn.id,a.id,e.c,e.root);assert.equal(readJSON(path.join(e.dir,'system/tasks.json')).length,1);const built=applyConversationAction(s.id,turn.id,turn.actions[1].id,e.c,e.root);assert.equal(built.result.workflow,'build');assert.deepEqual(built.result.sourceIds,[]);assert.equal(built.session.turns.at(-1).actions[1].status,'applied');
});
test('unselected source and arbitrary action proposals are rejected before state changes',t=>{const e=env(t,{configured:true});assert.throws(()=>parseConversationResponse(message('x',{},[{type:'build_feature',prompt:'Build a table',sourceIds:[crypto.randomUUID()]}]),e.c,e.root),/unavailable source/);assert.throws(()=>parseConversationResponse(message('x',{},[{type:'publish',url:'https://example.com'}]),e.c,e.root),/unsupported/);assert.throws(()=>parseConversationResponse(message('x',{},[{type:'settings',settings:{provider:'other'}}]),e.c,e.root),/supported settings/);});
test('conversation context keeps bounded prior turns and the editable business profile',t=>{const e=env(t,{configured:true}),s=createConversation('conversation',e.c,e.root);s.turns=Array.from({length:100},(_,i)=>({role:i%2?'assistant':'user',text:`turn ${i} `+'x'.repeat(3000)}));const data=conversationContext(s,{...e.c,businessProfile:{...e.c.businessProfile,businessName:'Studio'}},e.root);assert.equal(data.recent.length,12);assert.ok(data.summary.length<=14000);assert.equal(data.businessProfile.businessName,'Studio');assert.match(data.summary,/turn 87/);});
test('conversation jobs outrank queued reports while reports retain FIFO order',t=>{const e=env(t),report=enqueue(e.dir,'brief'),s=createConversation('onboarding',e.c,e.root),{job}=submitTurn(s.id,'Hello','r1',e.c,e.root);assert.equal(nextQueuedJob([e.dir,e.queue]).job.id,job.id);cancelConversation(s.id,e.c,e.root);assert.equal(nextQueuedJob([e.dir,e.queue]).job.id,report.id);});
test('three packs contain fictional marked records, examples and empty import templates',async t=>{const e=env(t);assert.equal(PACKS.length,3);for(const pack of PACKS){const result=await importPack(e.dir,pack.id);assert.match(result.sources[0].name,/^DEMO/);assert.equal(result.sources[0].origin,`demo:pack:${pack.id}`);assert.ok(pack.questions.length>=3);assert.ok(pack.commands.length>=3);assert.match(pack.example,/DEMONSTRATION/);await importPack(e.dir,pack.id);}assert.equal(sourcesFor(e.dir).length,3);assert.equal(contextFor(e.dir,e.c).sources.every(s=>s.demo),true);});
test('feature-scoped reports do not read other selected knowledge, metrics or shared tasks',async t=>{const e=env(t),a=await importBuffer(e.dir,Buffer.from('a,value\n1,2'),'a.csv'),b=await importBuffer(e.dir,Buffer.from('SECRET'),'b.md');atomicJSON(path.join(e.dir,'system/tasks.json'),[{title:'Private task'}]);const c={...e.c,metrics:[{sourceId:b.id}]};assert.equal(contextFor(e.dir,c,'',[a.id]).sources.length,1);assert.deepEqual(contextFor(e.dir,c,'',[a.id]).metrics,[]);assert.deepEqual(contextFor(e.dir,c,'',[a.id]).tasks,[]);assert.deepEqual(contextFor(e.dir,c,'',[]).sources,[]);});
test('request dispatcher preserves explicit endpoint shapes and unknown route fallback',async t=>{const e=env(t);const created=await handleConversationRequest({action:'conversation',method:'POST',data:{kind:'onboarding'},config:e.c,root:e.root});const fetched=await handleConversationRequest({action:'conversation',url:new URL(`http://localhost/?id=${created.session.id}`),config:e.c,root:e.root});assert.equal(fetched.session.id,created.session.id);assert.equal(await handleConversationRequest({action:'not-a-route',config:e.c,root:e.root}),null);});
test('new installs select normal-speed Kokoro while version 1 keeps its system voice',()=>{assert.equal(defaults().voice.engine,'kokoro');assert.equal(defaults().voice.speed,1);const old=validateConfig({version:1,voice:{engine:'system',speed:1.2}});assert.equal(old.voice.engine,'system');assert.equal(old.voice.speed,1.2);assert.equal(validateConfig({version:1}).voice.engine,'system');});
test('title survives model answer, brief preview and completion',async t=>{const e=env(t),s=createConversation('onboarding',e.c,e.root);await reply(e,s,'Call it My Studio',message('My Studio it is.',{title:'My Studio'}));assert.equal(previewOnboarding({},e.c,e.root).config.title,'My Studio');assert.equal((await completeOnboarding({},e.c,e.root)).config.title,'My Studio');});
test('completion, failure and applied actions advance session revisions',async t=>{const e=env(t,{configured:true}),s=createConversation('conversation',e.c,e.root);const done=await reply(e,s,'Add task',message('Here is a proposed task.',{},[{type:'task',title:'Review'}]));assert.equal(done.revision,2);const turn=done.turns.at(-1);assert.equal(applyConversationAction(s.id,turn.id,turn.actions[0].id,e.c,e.root).session.revision,3);const failed=await reply(e,s,'Try a reply','bad JSON');assert.equal(failed.revision,5);});
test('applying an older proposal during a reply interrupts it without leaving a stuck pending job',async t=>{const e=env(t,{configured:true}),s=createConversation('conversation',e.c,e.root),done=await reply(e,s,'Add a task',message('Review it.',{},[{type:'task',title:'Review'}])),turn=done.turns.at(-1),{job}=submitTurn(s.id,'Another question','next',e.c,e.root);await executeConversation(e.queue,e.c,job,async()=>{applyConversationAction(s.id,turn.id,turn.actions[0].id,e.c,e.root);return message('Stale');},{root:e.root});const current=getConversation(s.id,e.c,e.root);assert.equal(current.pendingJobId,null);assert.equal(current.status,'idle');assert.equal(current.turns.at(-1).role,'user');assert.equal(jobsFor(e.queue).find(j=>j.id===job.id).status,'cancelled');});
test('bounded progress stream validates session, reports new revisions and stops on abort',async t=>{const e=env(t),s=createConversation('onboarding',e.c,e.root),abort=new AbortController(),reader=conversationEvents(s.id,e.c,e.root,{signal:abort.signal,intervalMs:10}).getReader(),decode=value=>new TextDecoder().decode(value);assert.match(decode((await reader.read()).value),/event: progress/);submitTurn(s.id,'Hello','stream-1',e.c,e.root);assert.match(decode((await reader.read()).value),/"status":"queued"/);abort.abort();assert.equal((await reader.read()).done,true);assert.throws(()=>conversationEvents('missing',e.c,e.root),/Invalid conversation/);});
test('progress stream sends a heartbeat, expires, and supports explicit consumer cancellation',async t=>{const e=env(t),s=createConversation('onboarding',e.c,e.root),reader=conversationEvents(s.id,e.c,e.root,{intervalMs:10,heartbeatMs:1,durationMs:25}).getReader();await reader.read();assert.match(new TextDecoder().decode((await reader.read()).value),/heartbeat/);let ended=false;while(!ended)ended=(await reader.read()).done;assert.equal(ended,true);const second=conversationEvents(s.id,e.c,e.root).getReader();await second.read();await second.cancel();assert.equal((await second.read()).done,true);});
test('queue scope participates in deduplication and cancelled reports are never restarted',async t=>{const e=env(t),featureId=crypto.randomUUID(),a=enqueue(e.dir,'brief','Same',{featureId,sourceIds:['a']}),b=enqueue(e.dir,'brief','Same',{featureId,sourceIds:['b']});assert.notEqual(a.id,b.id);assert.equal(enqueue(e.dir,'brief','Same',{featureId,sourceIds:['a']}).id,a.id);assert.notEqual(enqueue(e.dir,'brief','Same',{featureId,sourceIds:[]}).id,enqueue(e.dir,'brief','Same',{featureId}).id);const file=path.join(e.dir,'system/jobs',a.id+'.json');atomicJSON(file,{...a,status:'cancelled'});let called=false;await executeJob(e.dir,e.c,a,async()=>{called=true;return 'Wrong';},{root:e.root});assert.equal(called,false);});
