import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {spawnSync} from 'node:child_process';
import {defaults,loadConfig,readJSON,atomicJSON} from '../runtime/config.mjs';
const script=path.resolve('scripts/configure.mjs');
function environment(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'argus-onboarding-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;}
function run(root,args){const r=spawnSync(process.execPath,[script,...args],{cwd:root,encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r;}
test('interrupted interview resumes without resetting previous answers',t=>{const root=environment(t),file=path.join(root,'answers.json');atomicJSON(file,{purpose:'Build a study routine',name:'Alex'});run(root,['--answers',file]);atomicJSON(file,{goals:['Finish the course']});run(root,['--answers',file]);const progress=readJSON(path.join(root,'.argus-onboarding.json'));assert.equal(progress.answers.name,'Alex');assert.deepEqual(progress.answers.goals,['Finish the course']);assert.equal(loadConfig(root).onboarded,false);});
test('each preset can complete onboarding and be customised later',t=>{for(const preset of ['business','creator','learning']){const root=environment(t),file=path.join(root,'proposed.json');atomicJSON(file,{preset,name:'Alex',goals:['Finish something useful']});run(root,['--from',file,'--confirmed']);assert.equal(loadConfig(root).preset,preset);assert.equal(readJSON(path.join(root,'.argus-onboarding.json')).stage,'complete');atomicJSON(file,{title:'My ARGUS'});run(root,['--from',file]);assert.equal(loadConfig(root).title,'My ARGUS');assert.deepEqual(loadConfig(root).goals,['Finish something useful']);}});
test('selected Obsidian vault retains existing notes and conventions',t=>{const root=environment(t),vault=path.join(root,'Selected vault');fs.mkdirSync(path.join(vault,'.obsidian'),{recursive:true});fs.writeFileSync(path.join(vault,'Welcome.md'),'# Keep my notes\n[[My conventions]]');fs.writeFileSync(path.join(vault,'.obsidian','app.json'),'{"useMarkdownLinks":false}');const proposed=path.join(root,'proposed.json');atomicJSON(proposed,{...defaults(),preset:'learning'});run(root,['--from',proposed,'--confirmed','--vault',vault]);assert.equal(loadConfig(root).workspace,path.join(fs.realpathSync(vault),'ARGUS'));assert.equal(fs.readFileSync(path.join(vault,'Welcome.md'),'utf8'),'# Keep my notes\n[[My conventions]]');assert.equal(fs.readFileSync(path.join(vault,'.obsidian/app.json'),'utf8'),'{"useMarkdownLinks":false}');});
test('changing a populated workspace is blocked without deleting its data',t=>{const root=environment(t),existing=path.join(root,'workspace');fs.mkdirSync(existing);fs.writeFileSync(path.join(existing,'notes.md'),'Keep');const proposed=path.join(root,'proposed.json');atomicJSON(proposed,{workspace:'new-workspace'});const r=spawnSync(process.execPath,[script,'--from',proposed],{cwd:root,encoding:'utf8'});assert.notEqual(r.status,0);assert.equal(fs.readFileSync(path.join(existing,'notes.md'),'utf8'),'Keep');assert.equal(loadConfig(root).workspace,'workspace');});
