'use client';
import {useEffect,useRef,useState} from 'react';
import {api} from '@/lib/api';
import type {Job,Source} from '@/lib/types';
import FeatureFrame,{type FeaturePreview} from './FeatureFrame';

interface Feature {id:string;name:string;description:string;kind:string;sourceIds:string[];activeVersion:string|null;versions:{id:string;createdAt:string}[]}
type BuildJob=Job&{sourceIds?:string[]};
const permissionLabels:Record<string,string>={'records.read':'Read feature records','records.write':'Save feature records','sources.read':'Read chosen sources','tasks.read':'Read your tasks','tasks.write':'Update your tasks','notes.read':'Read your notes','notes.write':'Add notes','reports.run':'Run AI reports'};
export default function BuildDesk({sources,onUpdated,onNotice,initialPrompt=''}:{sources:Source[];onUpdated:()=>void;onNotice:(message:string)=>void;initialPrompt?:string}){
  const [prompt,setPrompt]=useState(initialPrompt),[sourceIds,setSourceIds]=useState<string[]>([]);
  const [features,setFeatures]=useState<Feature[]>([]),[builds,setBuilds]=useState<BuildJob[]>([]),[preview,setPreview]=useState<FeaturePreview|null>(null);
  const [editingId,setEditingId]=useState<string|undefined>(),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const promptRef=useRef<HTMLTextAreaElement>(null);
  const refresh=async()=>{const r=await api<{features:Feature[];builds:BuildJob[]}>('/api/features');setFeatures(r.features);setBuilds(r.builds||[]);};
  useEffect(()=>{let active=true,polling=false;const poll=async()=>{if(polling)return;polling=true;try{const r=await api<{features:Feature[];builds:BuildJob[]}>('/api/features');if(active){setFeatures(r.features);setBuilds(r.builds||[]);}}catch(e){if(active)setError((e as Error).message);}finally{polling=false;}};void poll();const timer=setInterval(poll,1800);return()=>{active=false;clearInterval(timer);};},[]);
  const build=async()=>{if(!prompt.trim())return;setBusy(true);setError('');try{await api('/api/features/build',{prompt,featureId:editingId,sourceIds});setPrompt('');setEditingId(undefined);setPreview(null);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const openPreview=async(id:string,mode:'preview'|'active'='preview')=>{setBusy(true);try{const next=await api<FeaturePreview>(`/api/features/preview?id=${encodeURIComponent(id)}&mode=${mode}`);setPreview(next);setSourceIds(next.sourceIds||[]);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const activate=async(rollback=false)=>{if(!preview)return;setBusy(true);try{await api(`/api/features/${rollback?'rollback':'activate'}`,{id:preview.id,versionId:preview.versionId});await refresh();onUpdated();onNotice(rollback?'Previous feature version restored. Your records are preserved.':'Your new feature is ready.');await openPreview(preview.versionId,'active');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const restore=async(id:string,versionId:string)=>{setBusy(true);try{await api('/api/features/rollback',{id,versionId});setPreview(null);await refresh();onUpdated();onNotice('Feature version restored. Your records were preserved.');await openPreview(versionId,'active');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const revise=(f:Feature)=>{setEditingId(f.id);setPrompt(`Improve ${f.name}: `);setSourceIds(f.sourceIds||[]);setError('');promptRef.current?.focus();};
  const retry=(b:BuildJob)=>{setEditingId(b.featureId);setPrompt(b.question);setSourceIds(b.sourceIds??features.find(f=>f.id===b.featureId)?.sourceIds??(preview&&preview.id===b.featureId?preview.sourceIds:[]));setError('');promptRef.current?.focus();onNotice('Your original request and sources are ready. Review them, then build again.');};
  const pending=builds.some(b=>['queued','running'].includes(b.status));
  const missingSources=sourceIds.filter(id=>!sources.some(s=>s.id===id));
  return <div className="build-desk">
    <div className="build-intro"><span className="eyebrow">FROM AN IDEA TO A USEFUL TOOL</span><h2>What would make your work easier?</h2><p>Describe a dashboard, tracker, form or workflow. Explore a working preview, then choose when to add it to your ARGUS.</p></div>
    <div className="build-layout"><section className="build-form">
      <div className="example-prompts">{['A lead follow-up tracker','A client project board','A weekly content planner'].map(example=><button key={example} onClick={()=>{setEditingId(undefined);setPrompt(`Build ${example.toLowerCase()} with a useful dashboard, editable records, and a clear next action.`);}}>{example} ↗</button>)}</div>
      <form onSubmit={e=>{e.preventDefault();void build();}}><label className="student-field">{editingId?'Describe your changes':'Describe your feature'}<textarea ref={promptRef} value={prompt} onChange={e=>setPrompt(e.target.value)} rows={5} maxLength={4000} placeholder="Build a tracker for my client projects. I need a status, owner, deadline, and a view of overdue work…" required/></label>
        <details className="build-sources"><summary>Choose information this feature can use <span>{sourceIds.length} selected</span></summary><p>Previews can read selected sources. Your original files stay unchanged.</p>{sources.length?sources.map(s=><label className="student-task" key={s.id}><input type="checkbox" checked={sourceIds.includes(s.id)} onChange={e=>setSourceIds(ids=>e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/><span>{s.name}{s.demo&&<small className="demo-badge">DEMO</small>}</span></label>):<p>No sources added yet. The preview will use clearly labelled sample records.</p>}</details>
        {missingSources.length>0&&<div role="alert"><p>A previously selected source is unavailable. Add it again or remove it from this build.</p>{missingSources.map(id=><button type="button" key={id} onClick={()=>setSourceIds(ids=>ids.filter(sourceId=>sourceId!==id))}>Remove unavailable source {missingSources.indexOf(id)+1}</button>)}</div>}
        <button className="student-primary" disabled={busy||pending||!prompt.trim()||missingSources.length>0}>{pending?'Build in progress…':editingId?'Build a new version ↗':'Build a preview ↗'}</button>
        {editingId&&<button type="button" className="text-button" onClick={()=>setEditingId(undefined)}>Build as a separate feature</button>}
      </form>
      <section className="build-history"><h3>Builds</h3>{!builds.length&&<p>Your first preview will appear here.</p>}{builds.map(b=><div className="build-job" key={b.id}><span className={`status-dot ${b.status}`}/><div><strong>{b.summary||b.question||'Business feature'}</strong><small>{b.status}{b.error?` · ${b.error}`:''}</small></div>{b.versionId&&b.status==='completed'&&<button onClick={()=>void openPreview(b.versionId!)}>Preview ↗</button>}{['failed','cancelled'].includes(b.status)&&<button disabled={busy||pending} onClick={()=>retry(b)}>Review &amp; retry</button>}{['queued','running'].includes(b.status)&&<button onClick={()=>void api('/api/cancel',{id:b.id}).then(refresh).catch(e=>setError(e.message))}>Cancel</button>}</div>)}</section>
    </section><section className="build-preview-area" aria-label="Feature preview">
      {error&&<p className="inline-error" role="alert">{error}</p>}
      {preview?<><div className="preview-toolbar"><div><span className="eyebrow">{preview.mode==='active'?'ACTIVE FEATURE':'DRAFT PREVIEW · ORIGINALS UNCHANGED'}</span><h3>{preview.name}</h3></div>{preview.mode==='preview'&&<button className="student-primary" disabled={busy} onClick={()=>void activate()}>Use this version ↗</button>}</div><p className="preview-description">{preview.description}</p><FeatureFrame preview={preview} onNotice={onNotice} height={500}/><p className="preview-permissions">This feature can: {preview.permissions.length?preview.permissions.map(p=>permissionLabels[p]||p).join(' · '):'Display information only'}</p></>:<div className="build-empty"><span className="build-empty-mark">＋</span><h3>A new possibility, made yours.</h3><p>Your feature will appear here when the build is ready. You can test its layout and behaviour before activating it.</p><div><span>Describe</span><i>→</i><span>Preview</span><i>→</i><span>Make it yours</span></div></div>}
      <section className="installed-features"><h3>Your features <span>{features.filter(f=>f.activeVersion).length} active</span></h3>{!features.length&&<p>Build your first tool to begin your collection.</p>}{features.map(f=><article key={f.id}><div><h4>{f.name}</h4><p>{f.description}</p></div><div className="feature-actions">{f.activeVersion&&<button disabled={busy} onClick={()=>void openPreview(f.activeVersion!,'active')}>Open ↗</button>}<button onClick={()=>revise(f)}>Improve</button><details><summary>Versions</summary>{f.versions.map(v=><div key={v.id}><span>{new Date(v.createdAt).toLocaleString()}{v.id===f.activeVersion?' · active':''}</span><button disabled={busy} onClick={()=>void openPreview(v.id)}>Preview</button>{f.activeVersion&&v.id!==f.activeVersion&&<button disabled={busy} onClick={()=>void restore(f.id,v.id)}>Restore</button>}</div>)}</details></div></article>)}</section>
    </section></div>
  </div>;
}
