'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import type {State,Panel,VoiceSettings} from '@/lib/types';
import type {Strand,CoreReadout} from '@/lib/strands';
import {voice} from '@/lib/voice';
const City=dynamic(()=>import('./ui/CityCore'),{ssr:false});
const Markdown=dynamic(()=>import('react-markdown'),{ssr:false});
const START_PROMPT='Make ARGUS my own. Ask me questions one at a time, understand what I want to build, and customise it using my information. Keep the existing design unless I ask you to change it.';
const colours=['#ff6b5e','#7c5cff','#ffaf1f','#12b886','#2e9bef','#f45b9f'];
async function request(url:string,data?:unknown){const r=await fetch(url,data===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j;}
function Heading({title,tick}:{title:string;tick?:string}){return <div className="student-heading"><h2><i/>{title}</h2>{tick&&<span className="student-tick">{tick}</span>}</div>;}
function Dialog({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){
  const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const before=document.activeElement as HTMLElement;ref.current?.showModal();return()=>before?.focus();},[]);
  return <dialog className="student-dialog" ref={ref} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="student-dialog-inner"><header><h2>{title}</h2><button onClick={onClose} aria-label="Close dialog">×</button></header>{children}</div></dialog>;
}
export default function Console(){
  const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[toast,setToast]=useState(''),[now,setNow]=useState<Date|null>(null);
  const [modal,setModal]=useState<'setup'|'sources'|'voice'|'integrations'|'transcript'|null>(null),[report,setReport]=useState<{title:string;text:string}|null>(null);
  const [question,setQuestion]=useState(''),[task,setTask]=useState(''),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[speaking,setSpeaking]=useState(false),[recording,setRecording]=useState(false),[localMic,setLocalMic]=useState(false);
  const [voices,setVoices]=useState<SpeechSynthesisVoice[]>([]),[voicePrefs,setVoicePrefs]=useState<VoiceSettings|null>(null),[transcript,setTranscript]=useState<string[]>([]);
  const [celebrate,setCelebrate]=useState<{seq:number;tier:'minor'|'major'}|null>(null);
  const seen=useRef<Set<string>|null>(null),polling=useRef(false),recorder=useRef<MediaRecorder|null>(null),micRequest=useRef(0),micPending=useRef(false),micTimer=useRef<ReturnType<typeof setTimeout>|null>(null),commandRef=useRef<HTMLInputElement>(null);
  const refresh=useCallback(async()=>{if(polling.current)return;polling.current=true;try{const s:State=await request('/api/state');setState(s);setError('');voice.settings=s.config.voice;
    if(seen.current)for(const j of s.jobs){if(!seen.current.has(j.id+':'+j.status)&&j.status==='completed'){setToast(j.summary||'Your report is ready.');setCelebrate({seq:Date.now(),tier:'minor'});void voice.speak(j.summary||'Your report is ready.',true);}}
    seen.current=new Set(s.jobs.map(j=>j.id+':'+j.status));
  }catch(e){setError((e as Error).message);}finally{polling.current=false;}},[]);
  useEffect(()=>{void refresh();const t=setInterval(refresh,3000),clock=setInterval(()=>setNow(new Date()),1000);setNow(new Date());voice.init();voice.onSpeaking=setSpeaking;voice.onNotice=setToast;
    void request('/api/voice/health').then(j=>setLocalMic(Boolean(j.ok&&j.stt))).catch(()=>{});
    const list=()=>setVoices(window.speechSynthesis?.getVoices()||[]);list();window.speechSynthesis?.addEventListener('voiceschanged',list);
    return()=>{clearInterval(t);clearInterval(clock);voice.stop();micRequest.current++;if(micTimer.current)clearTimeout(micTimer.current);recorder.current?.stream.getTracks().forEach(t=>t.stop());window.speechSynthesis?.removeEventListener('voiceschanged',list);};},[refresh]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),6500);return()=>clearTimeout(t);},[toast]);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await refresh();}catch(e){setToast((e as Error).message);}finally{setBusy(false);}};
  const submit=async(id?:string)=>{const q=question.trim();if(['ask','draft'].includes(id||'ask')&&!q){commandRef.current?.focus();setToast('Type your question or describe the content you want.');return;}
    await act(async()=>{await request('/api/queue',{workflow:id,question:q});setTranscript(t=>[...t.slice(-39),q||id||'Ask']);setQuestion('');setToast('Queued. Your report will appear in Your work.');});};
  const openReport=async(id:string,source=false)=>{await act(async()=>setReport(await request(`/api/${source?'source':'report'}?id=${encodeURIComponent(id)}`)));};
  const startMic=useCallback(async()=>{
    if(micPending.current||recorder.current?.state==='recording')return;
    if(!localMic){setToast('Install local voice with npm run voice:setup, then restart ARGUS.');return;}
    const attempt=++micRequest.current;micPending.current=true;
    let stream:MediaStream|null=null;
    try{
      voice.stop();stream=await navigator.mediaDevices.getUserMedia({audio:true});
      if(attempt!==micRequest.current){stream.getTracks().forEach(t=>t.stop());return;}
      const r=new MediaRecorder(stream),parts:BlobPart[]=[];recorder.current=r;
      r.ondataavailable=e=>parts.push(e.data);
      r.onstop=async()=>{
        stream?.getTracks().forEach(t=>t.stop());if(micTimer.current)clearTimeout(micTimer.current);setRecording(false);setBusy(true);
        try{const b=new Blob(parts,{type:r.mimeType});const res=await fetch('/api/voice/stt',{method:'POST',body:b,headers:{'Content-Type':r.mimeType}});const j=await res.json();if(!res.ok)throw new Error(j.error);setQuestion(j.text||'');setToast(j.text?'Review your words, then press Run.':'No speech detected. Try again or type your request.');commandRef.current?.focus();}
        catch(e){setToast((e as Error).message);}finally{setBusy(false);}
      };
      r.start();setRecording(true);micTimer.current=setTimeout(()=>{if(r.state==='recording')r.stop();},60000);
    }catch{stream?.getTracks().forEach(t=>t.stop());setToast('Microphone unavailable or permission denied. Typed commands still work.');}
    finally{micPending.current=false;}
  },[localMic]);
  const stopMic=useCallback(()=>{micRequest.current++;if(recorder.current?.state==='recording')recorder.current.stop();},[]);
  useEffect(()=>{let held=false;const down=(e:KeyboardEvent)=>{if(e.key==='Escape')voice.stop();if(e.code==='Space'&&!e.repeat&&!document.querySelector('dialog[open]')&&!(e.target as HTMLElement).closest('input,textarea,button,select,[contenteditable]')){e.preventDefault();held=true;void startMic();}};const up=(e:KeyboardEvent)=>{if(e.code==='Space'&&held){held=false;stopMic();}};window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);};},[startMic,stopMic]);
  const c=state?.config;
  const moment=now&&c?new Intl.DateTimeFormat('en-GB',{timeZone:c.timezone,hour:'2-digit',minute:'2-digit',hour12:false}).format(now):'—';
  const date=now&&c?new Intl.DateTimeFormat('en',{timeZone:c.timezone,weekday:'short',month:'short',day:'numeric'}).format(now):'';
  const hour=Number(moment.split(':')[0]);const greeting=hour<12?'Good morning ☀':hour<17?'Good afternoon ☀':'Good evening ☾';
  const done=state?.tasks.filter(t=>t.done).length||0;
  const strands:Strand[]=(state?.metrics||[]).slice(0,8).map((m,i)=>({id:String(i),label:m.label,color:colours[i%6],health:'none',stale:Boolean(m.error),trend:0,activity:0,value:m.value===null?'—':m.value.toLocaleString(undefined,{maximumFractionDigits:2}),delta:null}));
  const readout:CoreReadout={big:state?.tasks.length?`${done}/${state.tasks.length}`:'Your next chapter',bigLabel:state?.tasks.length?'PRIORITIES COMPLETE':'MAKE ROOM FOR POSSIBILITY',bigHealth:'none',sub:[]};
  const panel=(p:Panel,index:number)=>{
    let content:React.ReactNode;
    if(p.type==='notes')content=<><div className="student-story"><span className="eyebrow">{c?.onboarded?'BUILT AROUND YOU':'A SPACE TO MAKE YOUR OWN'}</span><h3>{c?.onboarded?c.name:'What will you build?'}</h3><p>{c?.purpose||'Your goals, your knowledge, your next move.'}</p><div className="student-story-horizon" aria-hidden="true"><span/><span/><span/><span/><span/></div></div>{!c?.onboarded?<><p className="student-copy">Start a conversation in Claude Code or Codex. Your answers become your command centre.</p><button className="student-link" onClick={()=>setModal('setup')}>Make ARGUS yours <span>↗</span></button></>:<>{state?.notes.map((n,i)=><div className="student-row" key={i}><strong>{n.title}</strong><p>{n.text}</p></div>)}<p className="student-copy">{state?.sources.length?`${state.sources.length} source${state.sources.length===1?'':'s'} ready to explore.`:'Add your first source to give ARGUS useful context.'}</p><button className="student-link" onClick={()=>setModal('sources')}>Add knowledge <span>＋</span></button></>}</>;
    else if(p.type==='tasks')content=<>{state?.tasks.length?state.tasks.map(t=><label className={`student-task ${t.done?'done':''}`} key={t.id}><input type="checkbox" checked={t.done} onChange={()=>void act(()=>request('/api/tasks',{id:t.id,done:!t.done}))}/><span>{t.title}</span></label>):<p className="student-copy">Small steps. Meaningful progress.<br/>What deserves your attention today?</p>}<form className="student-inline" onSubmit={e=>{e.preventDefault();void act(async()=>{await request('/api/tasks',{title:task});setTask('');});}}><input aria-label="New priority" placeholder="Add a priority…" value={task} maxLength={300} onChange={e=>setTask(e.target.value)}/><button aria-label="Add priority" disabled={busy||!task.trim()}>＋</button></form></>;
    else if(p.type==='metrics')content=<>{state?.metrics.length?state.metrics.map((m,i)=><div className="student-metric" key={i}><span>{m.label}</span><strong>{m.value===null?'—':m.value.toLocaleString(undefined,{maximumFractionDigits:2})}<small>{m.unit}</small></strong><p>{m.error||m.period}</p></div>):<><div className="student-empty-metrics">{(c?.preset==='learning'?['Lessons completed','Study hours','Projects shipped']:c?.preset==='creator'?['Published pieces','Subscribers','Engagement']:['Revenue','Active clients','Qualified leads']).map(n=><div key={n}><span>{n}</span><b>—</b></div>)}</div><p className="student-copy small">No measurements connected. Import a table, then ask your assistant to confirm the columns, units and period.</p></>}</>;
    else if(p.type==='actions')content=<><div className="deck">{['Understand','Create'].map(group=><div className="deck-group" key={group}><div className="deck-group-label">{group}</div>{state?.workflows.filter(w=>w.group===group).map(w=><button className="deck-btn" disabled={!w.enabled||busy} key={w.id} title={w.reason||w.description} onClick={()=>void submit(w.id)}><span className="deck-dot"/>{w.label}<span className="deck-arrow">→</span></button>)}</div>)}</div><p className="student-copy small">{state?.workflows[0]?.reason||'Ask below. Your reports stay in your workspace.'}</p><button className="student-link small" onClick={()=>{setVoicePrefs(c?.voice||null);setModal('voice');}}>Voice & AI settings <span>↗</span></button></>;
    else if(p.type==='sources')content=<>{state?.sources.length?state.sources.slice(-5).reverse().map(s=><button className="student-source" key={s.id} onClick={()=>void openReport(s.id,true)}><span className={`student-dot ${s.status==='attachment'?'warn':''}`}/><span>{s.name}<small>{s.status==='attachment'?'Needs extraction':`${s.status} · ${new Date(s.capturedAt).toLocaleDateString()}`}{s.stale?' · saved snapshot':''}</small></span><span>↗</span></button>):<p className="student-copy">Bring your notes, tables and public links. Original files are preserved.</p>}<button className="student-link" onClick={()=>setModal('sources')}>Add a source <span>＋</span></button><button className="student-link small" onClick={()=>setModal('integrations')}>Connect accounts later <span>↗</span></button></>;
    else content=<>{state?.jobs.length?state.jobs.slice(0,5).map(j=><div className="student-job" key={j.id}><button disabled={!j.report} onClick={()=>void openReport(j.id)}><strong>{state.workflows.find(w=>w.id===j.workflow)?.label||j.workflow}</strong><small className={j.status==='failed'?'error':''}>{j.status} · {j.error||j.summary||j.question||'Working toward your goals'}</small></button>{['queued','running'].includes(j.status)&&<button className="student-cancel" onClick={()=>void act(()=>request('/api/cancel',{id:j.id}))}>Cancel</button>}</div>):<p className="student-copy">Briefings, plans and drafts will appear here. Open a report to explore the detail.</p>}</>;
    return <section className={`block student-block accent-${['coral','violet','sun','pink','sky','mint'][index%6]}`} key={p.id}><Heading title={p.title} tick={p.type==='actions'?(state?.runner.busy?'WORKING':state?.runner.alive?'READY':'OFFLINE'):p.type==='sources'?`${state?.sources.length||0} ADDED`:p.type==='tasks'?`${done} DONE`:undefined}/>{content}</section>;
  };
  return <main className="stage student-stage" style={c?{'--coral':c.accent} as React.CSSProperties:undefined}>
    {error&&<div className="conn-banner err" role="alert">{error} · Your saved data is preserved. Run npm run doctor.</div>}
    {toast&&<div className="console-toast" role="status">{toast}</div>}
    <div className="console student-console">
      <header className="console-top topbar"><div><div className="student-brand">{c?.title||'ARGUS'}</div><div className="student-tagline">{c?.preset==='learning'?'A LITTLE FURTHER, EVERY DAY':c?.preset==='creator'?'IDEAS INTO IMPACT':'YOUR WORLD, BROUGHT TOGETHER'}</div></div><div className="greeting">{greeting}<button className="student-status" onClick={()=>setModal('setup')}>{c?.onboarded?`${c.name}’s command centre`:'STUDENT EDITION · MAKE IT YOURS'}</button></div><div className="clock-wrap"><div className="clock">{moment}<span className="sec">:{now?String(now.getSeconds()).padStart(2,'0'):'—'}</span></div><div className="clock-date">{date}</div></div></header>
      <City mode={error?'error':recording?'listening':speaking?'speaking':state?.runner.busy?'working':'idle'} strands={strands} readout={readout} getLevel={voice.getLevel} celebrate={celebrate}/>
      <div className="console-left">{c?.panels.filter(p=>p.side==='left').map(panel)||<section className="block">Opening your command centre…</section>}</div>
      <div className="console-center"/>
      <div className="console-right">{c?.panels.filter(p=>p.side==='right').map(panel)}</div>
      <div className="console-bottom directive-bar"><section className="objective student-objective"><span className="eyebrow">YOUR PRIMARY DIRECTIVE</span><h2>{c?.goals[0]||'Make something that matters.'}</h2><div className="student-goals">{(c?.goals.slice(1)||[]).map((g,i)=><span key={i}><i/>{g}</span>)}</div><form className="student-command" onSubmit={e=>{e.preventDefault();void submit();}}><input ref={commandRef} aria-label="Ask ARGUS" placeholder="Ask, plan, or describe a draft…" maxLength={4000} value={question} onChange={e=>setQuestion(e.target.value)}/><button type="button" className={recording?'recording':''} aria-label={recording?'Stop recording':'Record a command'} title={localMic?'Hold Space or click to record':'Optional local voice setup required'} onClick={()=>recording?stopMic():void startMic()}>{recording?'■':'♩'}</button><button disabled={busy||!question.trim()||!state?.workflows.find(w=>w.id==='ask')?.enabled}>Run ↗</button></form></section><section className="block student-next"><Heading title="Next moves"/><p>{!c?.onboarded?'Start your setup conversation.':!state?.sources.length?'Bring in your first source.':!c.provider?'Choose your AI provider.':!state?.runner.alive?'Start the runner with npm start.':'Ask a useful question. Turn the answer into your next step.'}</p><button className="student-link" onClick={()=>setModal(!c?.onboarded?'setup':!state?.sources.length?'sources':'voice')}>Open <span>↗</span></button></section></div>
      <footer className="student-controls"><button onClick={()=>voice.stop()}>■ Stop Voice</button><button onClick={()=>{setVoicePrefs(c?.voice||null);setModal('voice');}}>Voice settings</button><button onClick={()=>setModal('transcript')}>Transcript</button><span>LOCAL WORKSPACE</span></footer>
    </div>
    {modal==='setup'&&<Dialog title="Make ARGUS yours" onClose={()=>setModal(null)}><p>You bring the ambition. ARGUS brings the space to work on it.</p><ol className="student-steps"><li>Open this folder in Claude Code or Codex.</li><li>Paste the prompt below. Your assistant asks one question at a time.</li><li>Choose your information and goals. Your existing design stays with you.</li></ol><blockquote>{START_PROMPT}</blockquote><button className="student-primary" onClick={()=>void navigator.clipboard.writeText(START_PROMPT).then(()=>setToast('Starting prompt copied.')).catch(()=>setToast('Select and copy the prompt above.'))}>Copy starting prompt</button><p className="student-copy">Already set up? Ask your assistant to add a panel, import another source or update your goals. Your own AI account is used.</p></Dialog>}
    {modal==='sources'&&<Dialog title="Bring your knowledge" onClose={()=>setModal(null)}><p>Files and public pages become searchable context. Originals are preserved in your local workspace.</p><label className="student-upload">{busy?'Importing…':'Choose a file or drop it here'}<input type="file" aria-label="Import a file" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void act(async()=>{const form=new FormData();form.append('file',f);const r=await fetch('/api/import/file',{method:'POST',body:form});const j=await r.json();if(!r.ok)throw new Error(j.error);setToast(j.duplicate?'This source is already imported.':`${j.name} added · ${j.status}`);});e.target.value='';}}/></label><p className="student-copy small">Up to 10 MB. Text, Markdown, CSV, JSON, HTML and text PDFs. Other formats are retained as attachments.</p><form className="student-inline" onSubmit={e=>{e.preventDefault();void act(async()=>{await request('/api/import/url',{url});setUrl('');setToast('Public page imported.');});}}><input type="url" aria-label="Public page URL" placeholder="https://your-public-page.com" value={url} onChange={e=>setUrl(e.target.value)} required/><button disabled={busy}>Add link</button></form><p className="student-copy">To import a selected folder, ask your coding assistant to run the import command for that folder. Hidden files, credentials and symlinks are excluded.</p><p className="student-copy small">AI tasks send selected excerpts to your chosen provider. Imported text cannot authorise actions.</p></Dialog>}
    {modal==='voice'&&<Dialog title="Voice & AI settings" onClose={()=>setModal(null)}><p>Choose the voice that feels right. Your AI account powers the thinking.</p><label className="student-field">AI provider<select value={c?.provider||''} onChange={e=>void act(()=>request('/api/settings',{provider:e.target.value||null}))}><option value="">Choose later</option><option value="claude">Claude Code {state?.providers.claude?.installed?'· installed':'· CLI needed'}</option><option value="codex">Codex {state?.providers.codex?.installed?'· installed':'· CLI needed'}</option></select></label>{voicePrefs&&<form onSubmit={e=>{e.preventDefault();void act(async()=>{await request('/api/settings',{voice:voicePrefs});setToast('Voice preferences saved.');});}}><label className="student-field">Speech engine<select value={voicePrefs.engine} onChange={e=>setVoicePrefs({...voicePrefs,engine:e.target.value as 'system'|'kokoro'})}><option value="system">System voice · no installation</option><option value="kokoro">Kokoro · optional local installation</option></select></label>{voicePrefs.engine==='system'?<label className="student-field">Available device voices<select value={voicePrefs.voiceURI} onChange={e=>setVoicePrefs({...voicePrefs,voiceURI:e.target.value})}><option value="">Device default</option>{voices.map(v=><option key={v.voiceURI} value={v.voiceURI}>{v.name} · {v.lang}{v.localService?' · local':''}</option>)}</select></label>:<label className="student-field">Local voice<select value={voicePrefs.kokoroVoice} onChange={e=>setVoicePrefs({...voicePrefs,kokoroVoice:e.target.value})}><option value="af_heart">Heart · American female</option><option value="am_michael">Michael · American male</option><option value="bf_emma">Emma · British female</option><option value="bm_george">George · British male</option></select></label>}<label className="student-field">Speed · {voicePrefs.speed.toFixed(1)}×<input type="range" min="0.5" max="2" step="0.1" value={voicePrefs.speed} onChange={e=>setVoicePrefs({...voicePrefs,speed:Number(e.target.value)})}/></label><label className="student-task"><input type="checkbox" checked={voicePrefs.muted} onChange={e=>setVoicePrefs({...voicePrefs,muted:e.target.checked})}/>Mute spoken responses</label><div className="student-buttons"><button type="button" onClick={()=>{voice.settings=voicePrefs;void voice.speak('Welcome to your space. Let’s make room for what comes next.');}}>Preview voice</button><button className="student-primary" disabled={busy}>Save preferences</button></div></form>}<p className="student-copy">For local male/female voices and microphone commands, run <code>npm run voice:setup</code>, then restart ARGUS. Downloads require internet; synthesis and transcription then run on your computer.</p></Dialog>}
    {modal==='integrations'&&<Dialog title="Connect when you need it" onClose={()=>setModal(null)}><p>Your first ARGUS works with files and public links. Private accounts need your own authorisation.</p>{['Advertising and analytics','Email and calendar','Sales and payments','Publishing and messaging'].map(x=><div className="student-row" key={x}><strong>{x}</strong><p>Not connected. Ask your assistant to implement the specific integration you need, using your own account.</p></div>)}<p className="student-copy">No accounts are connected and no external messages are sent by this starter.</p></Dialog>}
    {modal==='transcript'&&<Dialog title="This session" onClose={()=>setModal(null)}>{transcript.length?transcript.map((t,i)=><p className="student-row" key={i}>{t}</p>):<p>Your submitted requests will appear here. Reports are saved separately in Your work.</p>}<button onClick={()=>setTranscript([])}>Clear session transcript</button></Dialog>}
    {report&&<Dialog title={report.title} onClose={()=>setReport(null)}><div className="report-body"><Markdown>{report.text}</Markdown></div><button className="student-primary" onClick={()=>void voice.speak(report.text)}>Read opening aloud</button></Dialog>}
  </main>;
}
